[project]
name = "pyhabitats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mateusz Karandys", email = "mateusz.karandys@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "scikit-learn>=1.9.1",
    "simpleitk>=2.5.6",
]

[project.scripts]
pyhabitats = "pyhabitats:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
breaking_change_exclamation_in_title = true

[tool.ruff.lint]
extend-select = ["ANN"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"src/pyhabitats/types.py" = ["ANN401"]

[dependency-groups]
dev = [
    "marimo>=0.25.1",
    "matplotlib>=3.11.2",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-mock>=3.16.0",
]


